### ISSUE TITLE
addTermImprecision implementation not matching description

### ISSUE THREAD

**Issue by kingmanzhang** [TheJacksonLaboratory/Phenomiser#35]
We are currently swapping parent term for **noise** terms, instead of for **disease terms**. I think this is an error @pnrobinson agree? This code comes from LR2PG. I am going to correct it.

**Comment by kingmanzhang** [comment]
Yes, it's there as well. I have fixed Phenomiser. I could create a pull request to send it to LR2PG if you want.

**Comment by pnrobinson** [comment]
yes please

**Comment by vidarmehr** [comment]
I got the following error message when I ran Phenomiser in the imprecise mode:
Exception in thread "main" java.lang.IllegalArgumentException: no such vertex in graph: HP:0003621
	at org.jgrapht.graph.AbstractGraph.assertVertexExist(AbstractGraph.java:131)
	at org.jgrapht.graph.AbstractBaseGraph.outgoingEdgesOf(AbstractBaseGraph.java:497)
	at org.monarchinitiative.phenol.ontology.algo.OntologyAlgorithm.getParentTerms(OntologyAlgorithm.java:173)
	at org.jax.grid.PhenotypeOnlyHpoCaseSimulator.getNonRootRandomParentTerm(PhenotypeOnlyHpoCaseSimulator.java:221)
	at org.jax.grid.PhenotypeOnlyHpoCaseSimulator.lambda$getRandomTermsFromDisease$3(PhenotypeOnlyHpoCaseSimulator.java:255)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.SliceOps$1$1.accept(SliceOps.java:204)
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1351)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.jax.grid.PhenotypeOnlyHpoCaseSimulator.getRandomTermsFromDisease(PhenotypeOnlyHpoCaseSimulator.java:254)
	at org.jax.grid.PhenotypeOnlyHpoCaseSimulator.simulateCase(PhenotypeOnlyHpoCaseSimulator.java:276)
	at org.jax.grid.PhenotypeOnlyHpoCaseSimulator.simulateCases(PhenotypeOnlyHpoCaseSimulator.java:142)
	at org.jax.grid.GridSearch.run(GridSearch.java:78)
	at org.jax.cmd.GridSearchCommand.run(GridSearchCommand.java:92)
	at org.jax.PhenomiserApp.main(PhenomiserApp.java:85)

**Comment by kingmanzhang** [comment]
We are waiting for a fix to phenol
https://github.com/monarch-initiative/phenol/issues/199

**Comment by kingmanzhang** [comment]
@vidarmehr This fix should solve the issue.
https://github.com/monarch-initiative/phenol/tree/fixDiseaseParser

**Comment by vidarmehr** [comment]
@kingmanzhang Thank you, Aaron! I ran the code without any error.
Here is the result for the imprecise mode:
0	1	2	3	4	
1	0.0	0.02	0.01	0.01	0.01	
2	0.16	0.12	0.15	0.06	0.1	
3	0.36	0.29	0.17	0.12	0.27	
4	0.43	0.48	0.4	0.26	0.25	
5	0.62	0.5	0.49	0.41	0.36	
6	0.65	0.55	0.56	0.52	0.46	
7	0.71	0.75	0.6	0.62	0.48	
8	0.8	0.75	0.72	0.73	0.64	
9	0.84	0.8	0.82	0.79	0.78	
10	0.9	0.81	0.8	0.7	0.75

**Comment by kingmanzhang** [comment]
Trend looks reasonable to me!

**Comment by kingmanzhang** [comment]
I am closing this as this is solved issue. Let's open new tickets to discuss.
